language: java

jdk:
  - oraclejdk8

cache:
  directories:
  - .autoconf
  - $HOME/.m2

addons:
  apt:
    packages:
      - oracle-java8-installer

scripts:
  - mvn clean test jacoco:report coveralls:report

after_success:
  - ./scripts/oss-jfrog-deploy.sh